/**
 * Parses markdown and extracts all SQL code blocks.
 *
 * @returns An array of string content from each SQL code block.
 */
export function extractCode(markdown: string) {
  const codeBlocks = markdown.match(/```[\s\S]*?```/g) || [];
  const cleanedCode = codeBlocks.map((block) => {
    const lines = block.split('\n');
    return lines.slice(1, -1).join('\n').trim().concat('\n');
  });
  cleanedCode.push('\n');
  // TODO: eventually remove experimental warning.
  cleanedCode.push('/*\n * This code was generated by Copilot. It may contain errors or require modifications.\n */\n');
  return cleanedCode;
}
